import {
  Ban,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleUserRound,
  CircleX,
  Clock,
  Eye,
  EyeOff,
  Minus,
  Plus,
  Share,
  SlidersHorizontal,
  Star,
  Ticket,
  TriangleAlert,
  User,
  UserRoundPlus,
  Users,
  WifiOff,
  X,
} from "lucide-react-native";
import { NotificationIcon, RachaIcon } from "./brand-icons";

export const iconMap = {
  back: ChevronLeft,
  check: Check,
  success: CircleCheck,
  error: CircleX,
  eye: Eye,
  "eye-off": EyeOff,
  racha: RachaIcon,
  notification: NotificationIcon,
  profile: CircleUserRound,
  minus: Minus,
  plus: Plus,
  alert: TriangleAlert,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  share: Share,
  ticket: Ticket,
  user: User,
  "user-plus": UserRoundPlus,
  users: Users,
  calendar: Calendar,
  clock: Clock,
  ban: Ban,
  "wifi-off": WifiOff,
  star: Star,
  close: X,
  settings: SlidersHorizontal,
} as const;

export type TIconName = keyof typeof iconMap;
