// JSON real das RPCs (supabase/tests/event_sort_after.sql, fixture fx), capturado do banco local.
export const PROPOSAL_NONE = {
  state: "none",
  can_sort: true,
  consider_position: false,
  event_id: "ea9c9e05-eec6-441b-bde7-efaccd491ed3",
  line_count: 7,
  goalkeeper_count: 3,
  min_line_players: 6,
  confirmed_count: 10,
  not_attended_count: 0,
};

export const PROPOSAL_STALE = {
  state: "stale",
  can_sort: true,
  consider_position: false,
  event_id: "ea9c9e05-eec6-441b-bde7-efaccd491ed3",
  line_count: 6,
  goalkeeper_count: 3,
  min_line_players: 6,
  confirmed_count: 9,
  not_attended_count: 0,
};

// 11 confirmados, 6 vieram: faltam marcar 5 (supabase/tests/event_sort.sql, seção 10)
export const PROPOSAL_NOT_ATTENDED = {
  state: "none",
  can_sort: true,
  consider_position: false,
  event_id: "ea9c9e05-eec6-441b-bde7-efaccd491ed3",
  line_count: 6,
  goalkeeper_count: 0,
  min_line_players: 6,
  confirmed_count: 11,
  not_attended_count: 5,
};

export const PROPOSAL_READY = {
  mode: "normal",
  state: "ready",
  teams: [
    {
      players: [
        {
          kind: "member",
          stars: 4,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "1ccd024a-0826-4643-a985-42d6cb7cfdb5",
          avatar_path: null,
          display_name: "Jogador C",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 2,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "907a984d-f0af-4a3b-8f1d-b15adba1ddcb",
          avatar_path: null,
          display_name: "Jogador A",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 2,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "392b86b9-293c-4bfc-9324-da3e7954201f",
          avatar_path: null,
          display_name: "Jogador F",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
      ],
      star_sum: 8,
      is_active: true,
      goalkeeper: {
        kind: "member",
        guest_id: null,
        profile_id: "909ba22b-517b-4d41-ab85-dd9a5e489110",
        avatar_path: null,
        display_name: "Goleiro C",
      },
      is_complete: true,
      queue_order: 1,
      super_count: 0,
      team_id: "team-1",
      team_number: 1,
      player_count: 3,
    },
    {
      players: [
        {
          kind: "member",
          stars: 3,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "e4f16956-2880-4ccd-abf7-5277054b3670",
          avatar_path: null,
          display_name: "Jogador B",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 3,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "b0d86ef6-b5f1-4990-8adf-89b813502a19",
          avatar_path: null,
          display_name: "Jogador G",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 1,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "f670af08-5554-40ca-a8c0-55a7aeb59496",
          avatar_path: null,
          display_name: "Jogador E",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
      ],
      star_sum: 7,
      is_active: true,
      goalkeeper: {
        kind: "member",
        guest_id: null,
        profile_id: "d16e2443-db22-4f8e-8c18-2ae68198bdfb",
        avatar_path: null,
        display_name: "Goleiro B",
      },
      is_complete: true,
      queue_order: 2,
      super_count: 0,
      team_id: "team-2",
      team_number: 2,
      player_count: 3,
    },
    {
      players: [
        {
          kind: "member",
          stars: 5,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "7b25839b-f733-409e-8a19-acc35e3f48c5",
          avatar_path: null,
          display_name: "Jogador D",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
      ],
      star_sum: 5,
      is_active: true,
      goalkeeper: {
        kind: "member",
        guest_id: null,
        profile_id: "1e083d29-3aa6-431d-9a1d-c36d8b5ae39c",
        avatar_path: null,
        display_name: "Goleiro A",
      },
      is_complete: false,
      queue_order: 3,
      super_count: 0,
      team_id: "team-3",
      team_number: 3,
      player_count: 1,
    },
  ],
  balance: {
    diff: 1,
    label: "Muito equilibrado",
    score: 91.67,
    super_diff: 0,
    capped_by_super: false,
  },
  version: 1,
  can_sort: true,
  consider_position: false,
  event_id: "ea9c9e05-eec6-441b-bde7-efaccd491ed3",
  line_count: 7,
  confirmed_count: 10,
  not_attended_count: 0,
  super_warning: [],
  goalkeeper_count: 3,
  goalkeeper_queue: [],
  min_line_players: 6,
  goalkeepers_per_team: true,
};

export const PUBLISHED = {
  left: [
    {
      kind: "member",
      guest_id: null,
      plays_as: "OUTFIELD",
      did_attend: false,
      profile_id: "fee74d28-a0b3-44f1-b603-a794903fb19a",
      avatar_path: null,
      display_name: "Jogador B",
    },
  ],
  mode: "normal",
  state: "published",
  teams: [
    {
      players: [
        {
          kind: "member",
          stars: 5,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "1a989607-5dc4-47ee-8250-82567406d86c",
          avatar_path: null,
          display_name: "Jogador D",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 2,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "5d491f5d-b362-4f73-8695-c2dcfd95fc0d",
          avatar_path: null,
          display_name: "Jogador A",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 2,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "de030231-a16e-4914-8720-2e8f6fc10c37",
          avatar_path: null,
          display_name: "Jogador F",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
      ],
      star_sum: 9,
      is_active: true,
      goalkeeper: {
        kind: "member",
        guest_id: null,
        profile_id: "f4e4607d-bed2-481c-b9e3-90fa9fd1c602",
        avatar_path: null,
        display_name: "Goleiro B",
      },
      is_complete: true,
      queue_order: 1,
      super_count: 0,
      team_id: "team-1",
      team_number: 1,
      player_count: 3,
    },
    {
      players: [
        {
          kind: "guest",
          stars: 4,
          guest_id: "6c459142-f8e5-4d21-8204-266ca0231e12",
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: null,
          avatar_path: null,
          display_name: "Avulso Z",
          is_super_star: true,
          primary_position: "DEFENDER",
          secondary_position: "FORWARD",
        },
        {
          kind: "member",
          stars: 4,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "b61c67b2-f359-41af-9e3d-78ec8a811896",
          avatar_path: null,
          display_name: "Jogador C",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
        {
          kind: "member",
          stars: 1,
          guest_id: null,
          entered_at: "2026-10-03T13:44:47.95962+00:00",
          profile_id: "fcc58c2f-d969-4ae5-8c16-6f0018e84db4",
          avatar_path: null,
          display_name: "Jogador E",
          is_super_star: false,
          primary_position: "DEFENDER",
          secondary_position: "MIDFIELDER",
        },
      ],
      star_sum: 9,
      is_active: true,
      goalkeeper: {
        kind: "member",
        guest_id: null,
        profile_id: "f88a73dc-e9e9-4c55-b863-91eacb95e8e9",
        avatar_path: null,
        display_name: "Goleiro A",
      },
      is_complete: true,
      queue_order: 2,
      super_count: 1,
      team_id: "team-2",
      team_number: 2,
      player_count: 3,
    },
  ],
  viewer: {
    my_status: null,
    can_return: true,
    can_include: true,
    can_leave_any: true,
    can_leave_self: false,
  },
  balance: {
    diff: 1,
    label: "Muito equilibrado",
    score: 91.67,
    super_diff: 0,
    capped_by_super: false,
  },
  event_id: "7e9a0071-be64-45c5-b221-a7522ecaf395",
  conductor_id: "f5966a5a-4279-4ed8-ac53-60583b149dc2",
  confirmed_at: "2026-10-03T13:44:47.95962+00:00",
  event_status: "active",
  is_conductor: true,
  super_warning: [],
  goalkeeper_queue: [
    {
      kind: "member",
      guest_id: null,
      profile_id: "7f397ad6-f05c-4dfc-955a-e5c36540ceb6",
      avatar_path: null,
      queue_order: 1,
      display_name: "Goleiro C",
    },
  ],
  outfield_per_team: 3,
  goalkeepers_per_team: true,
  next_arrival: {
    kind: "queue",
    team_id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    team_number: 3,
  },
  bolinhas_availability: "ok",
  last_bolinhas: null,
  waiting_for_inclusion: [
    {
      plays_as: "OUTFIELD",
      profile_id: "3e254a94-9094-4bca-8df7-e51466d3d574",
      avatar_path: null,
      display_name: "Jogador G",
      queue_position: 1,
      reason: "waitlisted",
    },
    {
      plays_as: "OUTFIELD",
      profile_id: "c1a5e6f2-0b0d-4d52-9d0b-6f1f2f6f3a11",
      avatar_path: null,
      display_name: "Jogador H",
      queue_position: null,
      reason: "not_attended",
    },
  ],
};
